server:
  error:
    include-message: always

spring:
  profiles:
    active: prod
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

exchange-rate:
  base-currency: EUR
  precision-scale: 6
  provider-priorities: >
    FIXER_IO,
    EXCHANGE_RATE_HOST
  fixer:
    api:
      endpoint: https://data.fixer.io/api/latest
      access-key: ${FIXER_IO_ACCESS_KEY:a0625efcc893a5d260e119819bd4bf90}
  host:
    api:
      endpoint: https://api.exchangerate.host/live
      access-key: ${EXCHANGE_RATE_HOST_ACCESS_KEY:na}