server:
  error:
    include-message: always

spring:
  profiles:
    active: prod
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

exchange-rate:
  api:
    url: https://data.fixer.io/api/latest
    access-key: ${EXCHANGE_RATE_API_ACCESS_KEY}