server:
  error:
    include-message: always

spring:
  profiles:
    active: prod
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

exchange-rate:
  default-provider: FIXER_IO
  fixer:
    api:
      endpoint: https://data.fixer.io/api/latest
      access-key: ${FIXER_IO_ACCESS_KEY}
  host:
    api:
      endpoint: https://api.exchangerate.host/live
      access-key: ${EXCHANGE_RATE_HOST_ACCESS_KEY}